---
GoHeartbeatTools:
  logPath: "./logs/go-heartbeat.log"
  masterConnectSetting:
    name: "test-master-185"
    dbType: "mysql"
    #host: "172.16.1.185"
    host: "192.168.212.10:3306"
    userName: "heartbeat_user"
    password: "123456"
    charset: "utf8mb4"
    dbName: "go_heartbeat"
    tblName: "go_heartbeat_tbl"
    maxIdleConnections: 1
    maxOpenConnections: 3
  slaveConnectSetting:
    - name: "test-pro-db-slave01"
      dbType: "mysql"
      host: "192.168.212.11:3306"
      userName: "heartbeat_user"
      password: "123456"
      charset: "utf8mb4"
      dbName: "go_heartbeat"
      tblName: "go_heartbeat_tbl"
      maxIdleConnections: 1
      maxOpenConnections: 3
      monitorRoler:
        - during: 1
          laterSeconds: 20
        - during: 30
          laterSeconds: 10
        - during: 60
          laterSeconds: 5
    - name: "test-pro-db-slave02"
      dbType: "mysql"
      host: "192.168.212.11:3307"
      userName: "heartbeat_user"
      password: "123456"
      charset: "utf8mb4"
      dbName: "go_heartbeat"
      tblName: "go_heartbeat_tbl"
      maxIdleConnections: 1
      maxOpenConnections: 3
      monitorRoler:
        - during: 1
          laterSeconds: 20
        - during: 30
          laterSeconds: 10
        - during: 60
          laterSeconds: 5
