---
GoHeartbeatTools:
  logPath: "./logs/go-heartbeat.log"
  masterConnectSetting:
    name: "test-master-185"
    dbType: "mysql"
    host: "172.16.1.185"
    userName: "heartbeat_user"
    password: "123456"
    charset: "utf8mb4"
    dbName: "go_heartbeat"
    tblName: "go_heartbeat_tbl"
    maxIdleConnections: 1
    maxOpenConnections: 3
  slaveConnectSetting:
    - name: "test-pro-db-slave01"
      dbType: "aaa"
      host: ""
      userName: ""
      password: ""
      charset: ""
      dbName: ""
      tblName: ""
      maxIdleConnections: 1
      maxOpenConnections: 1
    - name: "test-pro-db-slave02"
      dbType: "bbb"
      host: ""
      userName: ""
      password: ""
      charset: ""
      dbName: ""
      tblName: ""
      maxIdleConnections: 1
      maxOpenConnections: 1

