---
GoHeartbeatTools:
  masterConnectSetting:
    name: "test-pro-db-master"
    dbType: "mysql"
    host: ""
    userName: ""
    password: ""
    charset: "utf8mb4"
    dbName: ""
    tblName: ""
    maxIdleConnections: 1
    maxOpenConnections: 5
  slaveConnectSettings:
    - name: "test-pro-db-slave01"
      dbType: ""
      host: ""
      userName: ""
      password: ""
      charset: ""
      dbName: ""
      tblName: ""
      maxIdleConnections: ""
      maxOpenConnections: ""
    - name: "test-pro-db-slave02"
      dbType: ""
      host: ""
      userName: ""
      password: ""
      charset: ""
      dbName: ""
      tblName: ""
      maxIdleConnections: ""
      maxOpenConnections: ""

